### PR TITLE
Update uuid to 1.1

### LINKED ISSUE #19: Upgrade uuid
uuid 0.8 is deprecated since april 2022. Can it be upgraded?

### PR DESCRIPTION
**Pull request by nstinus**
Fixes #19

### CODE REVIEW

**Comment by samgiles** [comment]
Thanks @nstinus, much appreciated. I'll find some time to merge and ship this change this week!

**Comment by nstinus** [comment]
Ping ^

**Comment by nstinus** [comment]
Thanks for this, unfortunately, since that patch was submitted, uuid got updated to 1.2.

**Comment by nstinus** [comment]
Thanks!

**Pull request merged**
